// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AntiPhisher.Domain.Models;

public partial class AIFeedback : Base
{
    public int FeedbackId { get; set; }

    public int AttemptId { get; set; }

    public string FeedbackText { get; set; }

    public string IndicatorsExplained { get; set; }

    public string ImprovementTips { get; set; }

    public string AIModel { get; set; }

    public int? PromptTokensUsed { get; set; }

    //public DateTime CreatedAt { get; set; }

    public virtual UserAttempt Attempt { get; set; }
}