// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AntiPhisher.Domain.Models;

public partial class Scenario
{
    public int ScenarioId { get; set; }

    public int CategoryId { get; set; }

    public int DifficultyId { get; set; }

    public int? CreatedByUserId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public bool IsPhishing { get; set; }

    public bool IsAIGenerated { get; set; }

    public bool IsActive { get; set; }

    public string SenderName { get; set; }

    public string SenderEmail { get; set; }

    public string RecipientName { get; set; }

    public string Subject { get; set; }

    public string EmailBodyHtml { get; set; }

    public string AttachmentUrl { get; set; }

    public string PhishingIndicators { get; set; }

    public string ExplanationHint { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<CampaignScenario> CampaignScenarios { get; set; } = new List<CampaignScenario>();

    public virtual Category Category { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual DifficultyLevel Difficulty { get; set; }

    public virtual ICollection<UserAttempt> UserAttempts { get; set; } = new List<UserAttempt>();

    public virtual ICollection<PhishingType> PhishingTypes { get; set; } = new List<PhishingType>();
}