// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AntiPhisher.Domain.Models;

/// <summary>
/// Lịch sử thực hành mô phỏng phishing của User.
/// DB Change: Thay thế UserAnswer (string "Safe"/"Phishing") bằng 3 trường boolean
///            mô tả hành vi thực tế của User khi gặp email phishing.
/// DB Change: UserAnswer → nullable (giữ lại cho backward compat, tự động tính từ behavior).
/// </summary>
public partial class UserAttempt
{
    public int AttemptId { get; set; }

    public int UserId { get; set; }

    public int ScenarioId { get; set; }

    public int? CampaignId { get; set; }

    // CHANGED: nullable — giá trị tự động tính từ behavior (Reported/Clicked/NoAction)
    public string? UserAnswer { get; set; }

    public bool IsCorrect { get; set; }

    public int Score { get; set; }

    public int? TimeTakenSeconds { get; set; }

    public int AttemptNumber { get; set; }

    public DateTime SubmittedAt { get; set; }

    // ===================================================
    // NEW: Bộ 3 trường hành vi Phishing thực tế
    // ===================================================

    /// <summary>User đã bấm vào link giả mạo trong email.</summary>
    public bool IsClickedLink { get; set; } = false;

    /// <summary>User đã nhập thông tin đăng nhập/thẻ tín dụng vào trang giả mạo.</summary>
    public bool IsCredentialLeaked { get; set; } = false;

    /// <summary>User đã nhấn nút "Báo cáo lừa đảo" — hành vi đúng đắn nhất.</summary>
    public bool IsReported { get; set; } = false;

    // Navigation
    public virtual ICollection<AIFeedback> AIFeedbacks { get; set; } = new List<AIFeedback>();
    public virtual Campaign Campaign { get; set; }
    public virtual Scenario Scenario { get; set; }
    public virtual User User { get; set; }
}
