// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AntiPhisher.Domain.Models;

public partial class UserAttempt
{
    public int AttemptId { get; set; }

    public int UserId { get; set; }

    public int ScenarioId { get; set; }

    public int? CampaignId { get; set; }

    public string UserAnswer { get; set; }

    public bool IsCorrect { get; set; }

    public int Score { get; set; }

    public int? TimeTakenSeconds { get; set; }

    public int AttemptNumber { get; set; }

    public DateTime SubmittedAt { get; set; }

    public virtual ICollection<AIFeedback> AIFeedbacks { get; set; } = new List<AIFeedback>();

    public virtual Campaign Campaign { get; set; }

    public virtual Scenario Scenario { get; set; }

    public virtual User User { get; set; }
}