// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AntiPhisher.Domain.Models;

public partial class Campaign
{
    public int CampaignId { get; set; }

    public int CreatedByUserId { get; set; }

    public int? CompanyId { get; set; }

    public string CampaignName { get; set; }

    public string Description { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<CampaignScenario> CampaignScenarios { get; set; } = new List<CampaignScenario>();

    public virtual ICollection<CampaignTeamAssignment> CampaignTeamAssignments { get; set; } = new List<CampaignTeamAssignment>();

    public virtual ICollection<CampaignUserAssignment> CampaignUserAssignments { get; set; } = new List<CampaignUserAssignment>();
    public virtual ICollection<CampaignPrerequisite> CampaignPrerequisites { get; set; } = new List<CampaignPrerequisite>();

    public virtual Company Company { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual ICollection<UserAttempt> UserAttempts { get; set; } = new List<UserAttempt>();
}