// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AntiPhisher.Domain.Models;

public partial class CampaignUserAssignment
{
    public int AssignmentId { get; set; }

    public int CampaignId { get; set; }

    public int UserId { get; set; }

    public DateTime AssignedAt { get; set; }

    public int? AssignedBy { get; set; }

    public virtual User AssignedByNavigation { get; set; }

    public virtual Campaign Campaign { get; set; }

    public virtual User User { get; set; }
}