// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AntiPhisher.Domain.Models;

public partial class CampaignScenario
{
    public int CampaignScenarioId { get; set; }

    public int CampaignId { get; set; }

    public int ScenarioId { get; set; }

    public int OrderIndex { get; set; }

    public virtual Campaign Campaign { get; set; }

    public virtual Scenario Scenario { get; set; }
}