// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AntiPhisher.Domain.Models;

public partial class DifficultyLevel
{
    public int DifficultyId { get; set; }

    public string LevelName { get; set; }

    public int LevelOrder { get; set; }

    public int BaseScore { get; set; }

    public virtual ICollection<Scenario> Scenarios { get; set; } = new List<Scenario>();
}