// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AntiPhisher.Domain.Models;

public partial class LoginHistory
{
    public int LoginHistoryId { get; set; }

    public int UserId { get; set; }

    public string IPAddress { get; set; }

    public string UserAgent { get; set; }

    public bool IsSuccess { get; set; }

    public string FailReason { get; set; }

    public DateTime LoggedAt { get; set; }

    public virtual User User { get; set; }
}