// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AntiPhisher.Domain.Models;

public partial class PhishingType
{
    public int PhishingTypeId { get; set; }

    public string TypeName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Scenario> Scenarios { get; set; } = new List<Scenario>();
}