// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AntiPhisher.Domain.Models;

public partial class Team
{
    public int TeamId { get; set; }

    public int CompanyId { get; set; }

    public int ManagerId { get; set; }

    public string TeamName { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<CampaignTeamAssignment> CampaignTeamAssignments { get; set; } = new List<CampaignTeamAssignment>();

    public virtual Company Company { get; set; }

    public virtual User Manager { get; set; }

    public virtual ICollection<TeamMember> TeamMembers { get; set; } = new List<TeamMember>();
}