// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AntiPhisher.Domain.Models;

public partial class User
{
    public int UserId { get; set; }

    public int? CompanyId { get; set; }

    public int RoleId { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }
    public string PasswordSalt { get; set; }

    public string FullName { get; set; }

    public string AvatarUrl { get; set; }

    public bool IsActive { get; set; }

    public bool IsEmailVerified { get; set; }

    public DateTime? LastLoginAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<CampaignTeamAssignment> CampaignTeamAssignments { get; set; } = new List<CampaignTeamAssignment>();

    public virtual ICollection<CampaignUserAssignment> CampaignUserAssignmentAssignedByNavigations { get; set; } = new List<CampaignUserAssignment>();

    public virtual ICollection<CampaignUserAssignment> CampaignUserAssignmentUsers { get; set; } = new List<CampaignUserAssignment>();

    public virtual ICollection<Campaign> Campaigns { get; set; } = new List<Campaign>();

    public virtual Company Company { get; set; }

    public virtual ICollection<LoginHistory> LoginHistories { get; set; } = new List<LoginHistory>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

    public virtual Role Role { get; set; }

    public virtual ICollection<Scenario> Scenarios { get; set; } = new List<Scenario>();

    public virtual ICollection<TeamMember> TeamMembers { get; set; } = new List<TeamMember>();

    public virtual ICollection<Team> Teams { get; set; } = new List<Team>();

    public virtual ICollection<UserAttempt> UserAttempts { get; set; } = new List<UserAttempt>();
    public List<Subscription>? Subscriptions { get; set; }
    public List<EmailVerification>? EmailVerifications { get; set; }
    public List<Payment>? Payments { get; set; }
}