// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AntiPhisher.Domain.Models;

public partial class vw_UserAttemptHistory
{
    public int AttemptId { get; set; }

    public int UserId { get; set; }

    public string FullName { get; set; }

    public string ScenarioTitle { get; set; }

    public string UserAnswer { get; set; }

    public bool IsCorrect { get; set; }

    public int Score { get; set; }

    public DateTime SubmittedAt { get; set; }

    public string FeedbackText { get; set; }
}